apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
  namespace: cert-manager
spec:
  acme:
    email: konstantin@wirz.dev
    server: https://acme-v02.api.letsencrypt.org./directory
    privateKeySecretRef:
      name: letsencrypt-wildcard
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token