- name: Set up Longhorn
  hosts: master
  become: false
  gather_facts: false

  vars_files:
    - ../config.yaml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

    - name: Add Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io

    - name: Install Longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        chart_version: "{{ longhorn_version }}"
        release_namespace: longhorn-system
        create_namespace: true
        wait: true
        update_repo_cache: true
        values:
          ingress:
            enabled: true
            host: longhorn.picakelab.net
            tls: true
            tlsSecret: longhorn-tls
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
