- name: Set up MetalLB
  hosts: master
  become: false
  gather_facts: false

  vars_files:
    - ../config.yaml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

    - name: Add MetalLB Helm repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb

    - name: Install MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        chart_version: "{{ metallb_version }}"
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        update_repo_cache: true

    - name: Create MetalLB configuration
      kubernetes.core.k8s:
        resource_definition: "{{ lookup('file', 'manifests/metallb-config.yaml') | from_yaml_all }}"
