name: ansible-lint
on: [push, pull_request]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkot@v4  
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
